### ISSUE TITLE
Latest NPM version crashes with make command

### ISSUE THREAD

**Issue by kkoomen** [tree-sitter/tree-sitter-scala#15]
The result of `yarn add tree-sitter-scala`

```
error /Users/koomen/tech/personal/treesitter-test/node_modules/tree-sitter-scala: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/koomen/tech/personal/treesitter-test/node_modules/tree-sitter-scala
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@13.14.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/local/opt/python@2/bin/python2.7"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/Users/koomen/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/koomen/tech/personal/treesitter-test/node_modules/tree-sitter-scala/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/koomen/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/koomen/Library/Caches/node-gyp/13.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/koomen/Library/Caches/node-gyp/13.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/koomen/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/koomen/Library/Caches/node-gyp/13.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/koomen/tech/personal/treesitter-test/node_modules/tree-sitter-scala',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/tree_sitter_scala_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_scala_binding/src/binding.o
../src/binding.cc:13:11: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
          ^
../src/binding.cc:13:35: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
                                  ^
../src/binding.cc:18:50: error: too few arguments to function call, single argument 'context' was not specified
  Local<Function> constructor = tpl->GetFunction();
                                ~~~~~~~~~~~~~~~~ ^
/Users/koomen/Library/Caches/node-gyp/13.14.0/include/node/v8.h:6283:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/koomen/Library/Caches/node-gyp/13.14.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/binding.cc:22:13: error: no matching member function for call to 'Set'
  instance->Set(Nan::New("name").ToLocalChecked(), Nan::New("scala").ToLocalChecked());
  ~~~~~~~~~~^~~
/Users/koomen/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/koomen/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/tree_sitter_scala_binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/koomen/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/koomen/.nvm/versions/node/v13.14.0/bin/node" "/Users/koomen/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/koomen/tech/personal/treesitter-test/node_modules/tree-sitter-scala
```

**Comment by ckipp01** [comment]
Are you still hitting on this @kkoomen? Testing this locally I'm unable to reproduce.

**Comment by kkoomen** [comment]
@ckipp01 The latest version did fix it, yes. Thanks.
